// API Configuration - Auto-generated by run_with_ngrok.py
// This file contains the correct API URL for the current environment
// API Configuration - Production (Render)

const API_CONFIG = {
  baseUrl: 'https://luna-2-62hl.onrender.com/api',
  isProduction: true
};

// Make it usable in browser
window.API_CONFIG = API_CONFIG;
