// API Configuration - Auto-generated by run_with_ngrok.py
// This file contains the correct API URL for the current environment

const API_CONFIG = {
  baseUrl: 'https://unenhanced-aromatically-kaylynn.ngrok-free.dev/api',
  isProduction: true
};

// Export for use in api.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = API_CONFIG;
}
