#!/usr/bin/env python3
"""
Run website with ngrok tunnels (FREE MODE)
Exposes both backend (Flask) and frontend (static files)
"""

import os
import sys
import subprocess
import time
from threading import Thread
import json

def start_backend():
    """Start Flask backend"""
    print("🔵 Starting Backend on localhost:5000...")
    os.chdir(os.path.join(os.path.dirname(__file__), 'backend'))
    subprocess.run([sys.executable, 'app.py'])

def start_frontend_server():
    """Start simple HTTP server for frontend (port 8000)"""
    time.sleep(2)  # Wait for backend to start
    print("🔵 Starting Frontend on localhost:8000...")
    os.chdir(os.path.join(os.path.dirname(__file__), 'frontend'))
    subprocess.run([sys.executable, '-m', 'http.server', '8000'])

def update_frontend_config(tunnel_url):
    """Update frontend config with ngrok tunnel URL"""
    try:
        config_path = os.path.join(os.path.dirname(__file__), 'frontend', 'config.js')
        config_content = f"""// API Configuration - Auto-generated by run_with_ngrok.py
// This file contains the correct API URL for the current environment

const API_CONFIG = {{
  baseUrl: '{tunnel_url}/api',
  isProduction: true
}};

// Export for use in api.js
if (typeof module !== 'undefined' && module.exports) {{
  module.exports = API_CONFIG;
}}
"""
        with open(config_path, 'w') as f:
            f.write(config_content)

        print(f"✅ Updated frontend config with tunnel URL: {tunnel_url}/api")

    except Exception as e:
        print(f"⚠️  Could not update frontend config: {e}")

def start_ngrok_tunnels():
    """Start ngrok tunnels"""
    time.sleep(4)  # Wait for services to start

    print("\n📡 Starting ngrok tunnel...")
    print("⏳ This may take a few seconds...\n")

    try:
        # Use the correct ngrok path
        ngrok_path = r"C:\Users\purvi\AppData\Local\Microsoft\WindowsApps\ngrok.exe"

        # Start ngrok tunnel for backend (port 5000) - API calls will work from anywhere
        print("📍 Creating tunnel for backend API (port 5000)...")
        backend_process = subprocess.Popen(
            [ngrok_path, 'http', '5000'],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            creationflags=subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
        )

        # Wait for tunnel to establish
        time.sleep(8)  # Give more time for tunnel to establish

        if backend_process.poll() is None:
            print("✅ Backend tunnel started successfully!")
        else:
            print("❌ Backend tunnel failed to start")
            return

        # Get the tunnel URL and update frontend config
        try:
            # Use curl or similar to get tunnel info
            import urllib.request
            import json
            with urllib.request.urlopen('http://localhost:4040/api/tunnels', timeout=5) as response:
                data = json.loads(response.read().decode())
                tunnels = data.get('tunnels', [])
                if tunnels:
                    tunnel_url = tunnels[0]['public_url']
                    print(f"🌐 Tunnel URL: {tunnel_url}")

                    # Update frontend config with the tunnel URL
                    update_frontend_config(tunnel_url)
                else:
                    print("⚠️  Could not get tunnel URL from ngrok API")
        except Exception as e:
            print(f"⚠️  Could not get tunnel URL: {e}")
            print("   API calls will use fallback detection")

        print("\n✅ Tunnel created successfully!\n")

        print("="*70)
        print("🌐 YOUR WEBSITE IS LIVE!")
        print("="*70)
        print("\n📱 Check ngrok dashboard for tunnel URL:")
        print("   http://localhost:4040")
        print("\n💡 Frontend: Access locally at http://localhost:8000")
        print("💡 API: Available globally via ngrok tunnel")
        print("\n⚠️  Note: API calls will work from any device!")
        print("💡 Press Ctrl+C to stop\n")
        print("="*70 + "\n")

        # Keep process running
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            print("\n\n🛑 Shutting down...")
            backend_process.terminate()
            sys.exit(0)

        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error starting tunnel: {e}")
        sys.exit(1)

def main():
    print("🚀 STARTING WEBSITE WITH NGROK\n")
    
    # Start backend in background thread
    backend_thread = Thread(target=start_backend, daemon=True)
    backend_thread.start()
    
    # Start frontend server in background thread
    frontend_thread = Thread(target=start_frontend_server, daemon=True)
    frontend_thread.start()
    
    # Start ngrok tunnels in main thread
    start_ngrok_tunnels()

if __name__ == '__main__':
    main()
